### ISSUE TITLE
Reviewer 2 comment 1

### ISSUE THREAD

**Issue by gavruskin** [gavruskin/curvatureNNI#14]
The paper is far from being self-contained. There are many concepts that are used without any explanation making the paper not easy to follow.  The proofs are sometimes sketched like the proof of Theorem 5 which relays in many known results that are not clearly mentioned. I suggest the authors to use more intuitive descriptions and formalise their proofs as much as possible.

**Comment by gavruskin** [comment]
Could you @matsen @cwhidden suggest anything particular to address this. I don't think we can make the paper self-contained without greatly increasing its length, which already is beyond what most journals would expect. Similarly, the proof of Theorem 5 will have to rely heavily on the STT paper and would not be understood in detail without reading STT first. So the way to go I think is to add more intuitive explanations. What do you think?

**Comment by gavruskin** [comment]
@matsen @cwhidden I think, modulo this comment, I'm done with the revision. I've put the comments to the editor and the reviewer in comments to the (now closed) issues. I'll write a response letter, copy those comments there, and will send everything back to the journal once you okay the revision.

**Comment by cwhidden** [comment]
I don't think we need to try to make the paper be self-contained, but should certainly try to address the reviewers concerns. I agree that adding more intuitive explanations is the way to go. I'll make a list of ideas here:

Lemma 4:
* Add a couple of sentences of proof strategy at the beginning of the proof. Maybe something like "We prove the bounds by providing exemplar trees with the specified degree and explaining why no tree can have a greater (or lesser) degree."

Theorem 5:
* This is the reviewer's main concern and should be carefully addressed. The proof is already very long, so we don't want to add too much. Maybe we could state Theorem 2.3 of STT outside the theorem and then add a couple of sentences describing how the proof works there?

Proposition 8
* tanglegrams aren't defined

**Comment by gavruskin** [comment]
Thanks @cwhidden! I've made all your three suggestions.
