### ISSUE TITLE
Reviewer 2 minor comments

### ISSUE THREAD

**Issue by gavruskin** [gavruskin/curvatureNNI#16]
- Page 2, Section 2 :  It is not clear what you mean with the phrase:  "We identify isomorphic trees."
- Please state what does DtT stand for.
- Page 3: It would be nice if the example in Fig. 2 shows all the three operations, that is also the swapping of the rank of two nodes.
- Page 4: The paragraph starting with "This hierarchy can be seen as a set of … " is not clear. Please give at least some intuition on what is a \tau-space.
- Page 5: define what convex means in the set of trees you are considering.
- Page 6 inside the proof of Lemma 4: "… no divergence event being younger than a taxon."Not clear what this means, this should hold for every phylogenetic tree.
- Page 6 inside the proof of Lemma 4: what is the aunt of a subtree?
- Page 6 last paragraph:  "The best known bound for NNI … ". You mean upper bound.
- Page 7 second paragraph inside the proof of Theorem 5: what are half-edges? Do you mean the middle point of an edge?
- Page 12: what are sampled ancestor trees?

**Comment by gavruskin** [comment]
I've gone through these. Could you @cwhidden @matsen have a look? Especially Fig. 2 -- I did try to be super careful but an extra check wouldn't hurt for sure!

**Comment by gavruskin** [comment]
I reopen the issue for now -- if you don't feel like I have to do anything extra about these, feel free to close after your pass.

**Comment by cwhidden** [comment]
I added one comment to your commit that needs to be addressed and rephrased the Page 6 inside Lemma 4 paragraph to say:

"The upper bound is attained by a caterpillar tree with all intervals short, every taxon being younger than every divergence event, and both taxa of the cherry being younger than at least one other taxon, that is, a caterpillar tree with internal nodes having ranks $n, \ldots, 2(n-1)$ and the ranks of the taxa in cherry $< n-1$."

I think part of the reason this was confusing was the negative way it was written "no divergence event being younger than a taxon" so I rephrased it more directly.

**Comment by cwhidden** [comment]
Looking at the response document, there are many parts where you simply say "Done" or "We have added a detailed explanation" but do not say what the changes were. Unless the reviewer suggested a change (e.g. on Page 6 last paragraph we meant upper bound), I suggest adding the new text to the response document. I did this for my above change, for example.

**Comment by gavruskin** [comment]
Thanks @cwhidden! I'll wait for @matsen and then make another pass. Yeah, I was going to expands the done's once we have the final version and the diff -- that way it'll be easier to point out to exact places where we are addressing the concerns.

**Comment by gavruskin** [comment]
Got rid of the done's.
